(display "reverse list  car-cdr \n")
(define (displaynewline x)
    (display x)
    (newline)
)
; 3.14
(define (reverse-list x)
    (define (loop x y)
        (if (null? x) 
            y
            (let ((temp (cdr x)))
                (set-cdr! x y)
                (loop temp x)
            )
        )
    )
    (loop x '())
)

(define x (list 1 2 3 4 5))
(displaynewline (reverse-list x))