(display "list\n")
(define (length items)
    (if (null? items)
        0
        (+ 1 (length (cdr items)))
    )
)
(define (length2 items)
    (define (length-iter a count )
        (if (null? a)
            count 
            (length-iter (cdr a) (+ 1 count))
        )
    )
    (length-iter items 0)
)
(define (list-append lista listb)
    (if (null? lista)
        listb
        (cons( (car lista) (list-append (cdr lista) listb)) )
    )
)
(define (list-ref item n)
    (if (= 0 n)
        (car item)
        (list-ref (cdr item ) (- n 1) )
    )
)
(define (displaynewline x)
    (display x)
    (newline)
)
(define list-one-four (list 1 2 3 4))
(define alist (list 1 2 3 4 6 7 99))
(define blist (list 1 4 9 16 25))
(displaynewline (cdr list-one-four))
(displaynewline (list-ref list-one-four 2))
(displaynewline (length list-one-four ))
(displaynewline (length2 list-one-four ))
(displaynewline (cdr (append alist blist)))
(displaynewline (list-append alist blist) )